name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'  # Replace with the desired .NET version

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build and Publish for Windows
        run: dotnet publish -c Release --self-contained true -r win-x64 --output ./Release/windows-x64 --framework net7.0 /p:PublishSingleFile=true /p:PublishTrimmed=true

      - name: Build and Publish for Linux x64
        run: dotnet publish -c Release --self-contained true -r linux-x64 --output ./Release/linux-x64 --framework net7.0 /p:PublishSingleFile=true /p:PublishTrimmed=true

      - name: Build and Publish for Linux ARM
        run: dotnet publish -c Release --self-contained true -r linux-arm --output ./Release/linux-arm --framework net7.0 /p:PublishSingleFile=true /p:PublishTrimmed=true

      - name: Build and Publish for macOS
        run: dotnet publish -c Release --self-contained true -r osx-x64 --output ./Release/macos-x64 --framework net7.0 /p:PublishSingleFile=true /p:PublishTrimmed=true

      - name: Build and Publish for macOS ARM
        run: dotnet publish -c Release --self-contained true -r osx-arm64 --output ./Release/macos-arm64 --framework net7.0 /p:PublishSingleFile=true /p:PublishTrimmed=true

      - name: Remove Existing Zip Directories
        run: rm -rf ./Notes/Releases/*.zip

      - name: Zip Directories
        run: |
          cd ./Notes/Releases
          find . -type d -exec zip -r {}.zip {} \;
          cd ../..

      - name: Update Releases
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./Notes/Releases/**/*.zip
          name: Release Asset
          tag_name: ${{ github.ref }}
